const TermsAndConditionsPage = () => {
  return (
    <div 
      className="bg-cover bg-center bg-fixed font-body text-gray-800"
      style={{ backgroundImage: "url('/uploads/fullbg_Desktop.webp')" }}
    >
      <div className="bg-white bg-opacity-75 py-12">
        <div className="container mx-auto px-4">
          <div className="bg-white bg-opacity-90 p-8 md:p-12 rounded-xl shadow-2xl max-w-4xl mx-auto">
            <h1 className="text-4xl lg:text-5xl font-heading mb-8 text-center text-gray-900">Terms and Conditions</h1>
            <div className="prose lg:prose-xl max-w-none text-justify">
              <p className="italic text-sm text-center">This Document Is An Electronic Record In Terms Of Information Technology Act, 2000 And Rules There Under As Applicable And The Amended Provisions Pertaining To Electronic Records In Various Statutes As Amended By The Information Technology Act, 2000. This Electronic Record Is Generated By A Computer System And Does Not Require Any Physical Or Digital Signatures.</p>
              <p>Welcome to the Kama Ayurveda.</p>
              <p>Kama Ayurveda provides the content and services available on this website to you subject to the following Terms and Conditions, our Privacy Policy, Payment Policy and other terms and conditions and policies which you may find throughout our website in connection with certain functionality, features or promotions as well as customer service, all of which are deemed a part of and included within these terms and conditions (collectively, "Terms and Conditions"). By accessing or using this website, you are acknowledging that you have read, understood, and you agree, without limitation or qualification, to be bound by these Terms and Conditions in this Agreement, so please read this carefully before proceeding.</p>
              
              <h2 className="text-2xl font-heading mt-8 mb-4">Privacy</h2>
              <p>Please review our privacy-policy so that you may understand our privacy practices.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Payment Policy</h2>
              <p>Please see our Payment Policy to understand the purchase processes of our products.</p>
              <p>All international shipping orders may attract local duties applicable in that country and accordingly the customer will have to pay such local duties/taxes.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Products And Services For Personal Use</h2>
              <p>The products and services described on this website, and any samples thereof we may provide to you, are for personal use only. You may not sell or resell any of the products or services, or samples thereof, you receive from us. We reserve the right, with or without notice, to cancel or reduce the quantity of any products or services to be provided to you that we believe, in our sole discretion, may result in the violation of our Terms and Conditions.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Accuracy Of Information</h2>
              <p>We attempt to be as accurate as possible when describing our products on the website. However, except to the extent implied by applicable law, we do not warrant that the product descriptions, colours, information or other content available on the website are accurate, complete, reliable, current, or error-free.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Intellectual Property</h2>
              <p>All information and content available on the website and its "look and feel", including but not limited to trademarks, logos, service marks, text, graphics, logos, button icons, images, audio clips, data compilations and software, and the compilation and organization thereof (collectively, the "Content") is the property of Kama Ayurveda, our Affiliates, partners or licensors, and is protected by laws of India, including laws governing all applicable forms of intellectual property.</p>
              <p>Except as set forth in the limited licenses in Section 6, or as required under applicable law, neither the Content nor any portion of this website may be used, reproduced, duplicated, copied, sold, resold, accessed, modified, or otherwise exploited, in whole or in part, for any purpose without our express, prior written consent.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Limited Licenses</h2>
              <p>We grant you a limited, revocable, and non-exclusive license to access and make personal use of the website. This limited license does not include the right to:</p>
              <ul className="list-disc list-inside">
                <li>Frame or utilize framing techniques to enclose the website or any portion thereof;</li>
                <li>Republish, redistribute, transmit, sell, license or download the website or any and/or all Content (except caching or as necessary to view the website);</li>
                <li>Make any use of the website or any and/or all Content other than personal use;</li>
                <li>Modify, reverse engineer or create any derivative works based upon either the website or any and/or all Content;</li>
                <li>Collect account information for the benefit of yourself or another party;</li>
                <li>Use any meta tags or any other "hidden text" utilizing any and/or all Content; or</li>
                <li>Use software robots, spiders, crawlers, or similar data gathering and extraction tools, or take any other action that may impose an unreasonable burden or load on our infrastructure. You must retain, without modification, all proprietary notices on the website or affixed to or contained in the website.</li>
              </ul>

              <h2 className="text-2xl font-heading mt-8 mb-4">Your Obligations And Responsibilities</h2>
              <p>In the access or use of the website, you shall comply with these Terms and Conditions and the special warnings or instructions for access or use posted on the website. You shall act always in accordance with the law, custom and in good faith. You may not make any change or alteration to the website or any Content or services that may appear on this website and may not impair in any way the integrity or operation of the website. Without limiting the generality of any other provision of these Terms and Conditions, if you default negligently or willfully in any of the obligations set forth in these Terms and Conditions, you shall be liable for all the losses and damages that this may cause to Kama Ayurveda, our Affiliates, partners or licensors.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Third Party Links</h2>
              <p>We are not responsible for the content of any off-website pages or any other websites linked to or from the Kama Ayurveda website. Links appearing on this website are for convenience only and are not an endorsement by us, our Affiliates or our partners of the referenced content, product, service, or supplier. Your linking to or from any off-website pages or other websites is at your own risk. We are in no way responsible for examining or evaluating, and we do not warrant the offerings of, off-website pages or any other websites linked to or from the site, nor do we assume any responsibility or liability for the actions, content, products, or services of such pages and websites, including, without limitation, their privacy policies and terms and conditions. You should carefully review the terms and conditions and privacy policies of all off-website pages and other websites that you visit.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Special Features, Functionality And Events</h2>
              <p>Kama Ayurveda may offer certain special features and functionality or events (such as contests, sweepstakes or other offerings) which may (a) be subject to terms of use, rules and/or policies in addition to or in lieu of these Terms and Conditions; and (b) be offered by us or by third parties. If so, we will notify you of this and if you choose to take advantage of these offerings, you agree that your use of such offerings will be subject to such additional or separate terms of use, rules and/or policies.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Submissions</h2>
              <p>It is our policy to decline unsolicited suggestions and ideas. Notwithstanding our policy with regard to unsolicited suggestions and ideas, any inquiries, feedback, suggestions, ideas or other information you provide us (collectively, "Submissions") will be treated as non-proprietary and non-confidential. Subject to the terms of our Privacy Policy, by transmitting or posting any Submission, you hereby grant us the right to copy, use, reproduce, modify, adapt, translate, publish, license, distribute, sell or assign the Submission in any way as we see fit, including but not limited to copying in whole or in part, creating derivative works from, distributing and displaying any Submission in any form, media, or technology, whether now known or hereafter developed, alone or as part of other works, or using the Submission within or in connection with our products or services. You also acknowledge that your Submission will not be returned and we may use your Submission, and any ideas, concepts or know how contained therein, without payment of money or any other form of consideration, for any purpose including, without limitation, developing, manufacturing, distributing and marketing products.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">User Content</h2>
              <p>When you transmit, upload, post, e-mail or otherwise make available data, text, software, music, sound, photographs, graphics, images, videos, messages or other materials ("User Content") on the website, you are entirely responsible for such User Content. Such User Content constitutes a Submission under Section 10 above. This means that all third parties, and not we, are entirely responsible for all User Content that they post to the website. You agree not to engage in or assist or encourage others to engage in transmitting, uploading, posting, e-mailing or otherwise making available on the website User Content that (a) is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, pornographic, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; (b) you do not have a right to make available under any law or under contractual or fiduciary relationships; (c) is known by you to be false, inaccurate or misleading; (d) you were compensated for or granted any consideration by any third party; or (e) infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party. In addition, you agree not to transmit, upload, post, e-mail, or otherwise make available any software viruses, unsolicited or unauthorized advertising, solicitation or promotional material, including chain letters, mass mailings, or any form of "spam." You further agree not to (i) impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with any person or entity; (ii) "stalk" or otherwise harass including advocating harassment of another, entrap or harm any third party including harming minors in any way; (iii) forge headers or otherwise manipulate identifiers in order to disguise the origin of any User Content; (iv) intentionally or unintentionally violate any applicable local, state, national or international law; or (v) collect or store personally identifiable data about other users.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Copyright Complaints</h2>
              <p>We respect the intellectual property of others. If you believe that a work has been copied on the website in a way that constitutes copyright infringement, please click here to find out how to notify us of a claimed infringement.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Representations And Warranties And Limitation Of Liability</h2>
              <p>Kama Ayurveda makes no representations or warranties of any kind whatsoever, express or implied, in connection with these terms and conditions or the site, including but not limited to warranties of merchantability, non-infringement or fitness for a particular purpose, except to the extent such representations and warranties are not legally excludable.</p>
              <p>You agree that, to the fullest extent permitted by applicable law, Kama Ayurveda will not be responsible or liable (whether in contract, tort (including negligence) or otherwise), under any circumstances, for any (a) interruption of business; (b) access delays or access interruptions to the site; (c) data non-delivery, misdelivery, corruption, destruction or other modification; (d) loss or damages of any sort incurred as a result of dealings with or the presence of off-website links on the website; (e) computer viruses, system failures or malfunctions which may occur in connection with your use of the site, including during hyperlink to or from third party websites (f) any inaccuracies or omissions in content or (g) events beyond our reasonable control.</p>
              <p>Further, to the fullest extent permitted by law, Kama Ayurveda will not be liable for any indirect, special, punitive, incidental, or consequential damages of any kind (including lost profits) related to the site or your use thereof regardless of the form of action whether in contract, tort (including negligence) or otherwise, even if we have been advised of the possibility of such damages and in no event shall our maximum aggregate liability exceed Indian Rupees 2000 only.</p>
              <p>You agree that no claims or action arising out of, or related to, the use of the website or these terms and conditions may be brought by you more than one (1) year after the cause of action relating to such claim or action arose.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Disputes</h2>
              <p>With respect to any dispute regarding the website, all rights and obligations and all actions contemplated by these Terms and Conditions shall be governed by the laws of India and the courts of New Delhi, India, as if the Terms and Conditions were a contract wholly entered into and wholly performed within New Delhi, India, subject to foreign legal mandatory provisions. To the fullest extent permitted by applicable law, any dispute, differences or claim arising out your visit to the Kama Ayurveda website shall be referred to the sole Arbitrator appointed by the Chairman and Managing Director of Kama Ayurveda in accordance with the law. The venue of such arbitration shall be at New Delhi, India and the award of the Arbitrator shall be final and binding on all parties and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these Terms and Conditions shall be joined to an arbitration involving any other party subject to these Terms and Conditions, whether through class arbitration proceedings or otherwise.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">Consent To Receive Notices Electronically By Posting On The Website And Via Email</h2>
              <p>You consent to receive any agreements, notices, disclosures and other communications (collectively, "Notices") to which these Terms and Conditions refer from us electronically including without limitation by e-mail or by posting notices on this website. You agree that all Notices that we provide to you electronically satisfy any legal requirement that such communications be in writing. To withdraw your consent to receive Notices electronically, you must notify us of your withdrawal of such consent by emailing us at care@kamaayurveda.in and discontinue your use of this website. In such event, all rights granted to you pursuant to these Terms and Conditions, including but not limited to the limited licenses set forth in Section 6 hereof, shall automatically terminate. Unfortunately, we cannot provide the benefits of this website to any user that cannot consent to receipt of Notices electronically.</p>
              <p>Please note that this consent to receive Notices is entirely separate from any election you may make with respect to receipt of marketing communications. Your options with respect to receipt of marketing communications are set forth in our Privacy Policy.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">E-Gift Cards (Terms & Conditions)</h2>
              <ul className="list-disc list-inside">
                <li>The gift card can be loaded in multiples of INR 500 with a minimum value of Rs 1000.</li>
                <li>The gift card is valid for a period of 12 months from the date of issue.</li>
                <li>The gift card is redeemable only on the Kama Ayurveda India website and at our exclusive brand outlets.</li>
                <li>The gift card cannot be used to purchase another gift card.</li>
                <li>The gift card can be used for multiple transactions until the value is exhausted.</li>
                <li>If the order value exceeds the gift card amount, the balance can be paid using other available payment options.</li>
                <li>If the order value is less than the gift card amount, the remaining balance will be stored in the gift card for future use.</li>
                <li>The gift card cannot be exchanged for cash or credit.</li>
                <li>The gift card is non-transferable and can only be used by the recipient.</li>
                <li>Kama Ayurveda is not responsible for lost, stolen, or damaged gift cards.</li>
                <li>The gift card cannot be clubbed with any other promotion or benefit.</li>
              </ul>

              <h2 className="text-2xl font-heading mt-8 mb-4">General</h2>
              <p>You acknowledge and agree that these Terms and Conditions constitute the complete and exclusive agreement between us concerning your use of the website, and supersede and govern all prior proposals, agreements, or other communications.</p>
              <p>We reserve the right, in our sole discretion, to change these Terms and Conditions at any time by posting the changes on the website and providing notice of such change. Any changes are effective immediately upon posting to the Site and release of notice of such change. Your continued use of the website thereafter constitutes your agreement to all such changed Terms and Conditions. We may, with or without prior notice, terminate any of the rights granted by these Terms and Conditions. You shall comply immediately with any termination or other notice, including, as applicable, by ceasing all use of the website.</p>
              <p>Nothing contained in these Terms and Conditions shall be construed as creating any agency, partnership, or other form of joint enterprise between us. Our failure to require your performance of any provision hereof shall not affect our full right to require such performance at any time thereafter, nor shall our waiver of a breach of any provision hereof be taken or held to be a waiver of the provision itself. In the event that any provision of these Terms and Conditions shall be unenforceable or invalid under any applicable law or be so held by any applicable arbitral award or court decision, such unenforceability or invalidity shall not render these Terms and Conditions unenforceable or invalid as a whole but these Terms and Conditions shall be modified, to the extent possible, by the adjudicating entity to most fully reflect the original intent of the parties as reflected in the original provision.</p>

              <h2 className="text-2xl font-heading mt-8 mb-4">KAMA AYURVEDA LOYALTY PROGRAM</h2>
              <p>Welcome to Kama Ayurveda’s Loyalty Program. By enrolling in and participating in the program, you agree to abide by the following Terms & Conditions. Please read them carefully to understand your rights and responsibilities as a member.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Membership Tiers & Benefits</h3>
              <p>Our loyalty program is structured into four tiers, each offering a unique set of benefits. Your tier is determined by your cumulative spend over a 365-day period.</p>
              <p>On your first purchase of a minimum ₹4000 & above, you get an additional 500 loyalty points credited to your account.</p>
              <h4 className="text-lg font-heading mt-4 mb-2">A. The Seeker (₹0 – ₹10,000 cumulative spend)</h4>
              <ul className="list-disc list-inside">
                <li>Earn 1 point for every ₹100 spent</li>
                <li>Early access to new launches and sales</li>
                <li>Birthday rewards and special offers</li>
              </ul>
              <h4 className="text-lg font-heading mt-4 mb-2">B. The Believer (₹10,001 – ₹25,000 cumulative spend)</h4>
              <ul className="list-disc list-inside">
                <li>Earn 1.25 points for every ₹100 spent</li>
                <li>All benefits of The Seeker tier</li>
                <li>Complimentary shipping on all orders</li>
                <li>Exclusive access to members-only events</li>
              </ul>
              <h4 className="text-lg font-heading mt-4 mb-2">C. The Insider (₹25,001+ cumulative spend)</h4>
              <ul className="list-disc list-inside">
                <li>Earn 1.5 points for every ₹100 spent</li>
                <li>All benefits of The Believer tier</li>
                <li>Personalized skincare consultations</li>
                <li>Priority customer support</li>
              </ul>
              <h4 className="text-lg font-heading mt-4 mb-2">D. The Master (For our most consistent shoppers)</h4>
              <p>This is an invite-only tier for our most loyal and engaged shoppers. Reserved for those who have demonstrated a consistent commitment to Kama Ayurveda, this tier offers the highest level of exclusivity and rewards.</p>
              <ul className="list-disc list-inside">
                <li>Pre-launch invites to experience new launches before anyone else</li>
                <li>Exclusive service appointments to guide you on your skincare journey</li>
                <li>Dedicated customer care service for personalized support</li>
              </ul>
              <p>All tiers enjoy a 365-day point validity, ensuring you have ample time to redeem your earned points. Your tier status is reviewed annually, and your benefits will continue as long as you meet the spending criteria within the membership period.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Earning & Redeeming Points</h3>
              <p>Points are earned on every purchase made at Kama Ayurveda stores or online.</p>
              <p><strong>1 Point = 1 Rupee</strong></p>
              <p>Points are valid for 365 days from the date of issue. Expired points cannot be reinstated.</p>
              <p>Points can be redeemed only at Kama Ayurveda stores and the official website. They cannot be exchanged for cash or transferred between accounts.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Account Access & Management</h3>
              <p>Members can check their points balance, tier status, and rewards by logging into their account on the Kama Ayurveda website or visiting a store. All communication regarding your membership, including points balance, offers, and rewards, will be shared via SMS / Whatsapp / Email.</p>
              <p>In case of discrepancies, members are advised to contact customer care within 30 days of the transaction.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Birthday Rewards</h3>
              <p>Members must ensure their date of birth is correctly entered at the time of enrollment to receive birthday rewards. These rewards will be credited automatically and must be redeemed within the specified validity period.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Program Exclusions & Limitations</h3>
              <p>Points will not be awarded on purchases made with gift cards or on heavily rewarded promotional items.</p>
              <p>In case of any canceled, returned, or refunded orders, earned points will be revoked.</p>
              <p>Points earned through fraudulent transactions or account misuse will be revoked.</p>
              <p>Kama Ayurveda reserves the right to modify, suspend, or terminate the Program, benefits, or these Terms & Conditions at any time without prior notice.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Cancellation & Termination of Membership</h3>
              <p>Members can opt out of the Program at any time by contacting customer care. If a membership is found to be in violation of Program policies, Kama Ayurveda reserves the right to cancel the membership and forfeit accumulated points.</p>
              <h3 className="text-xl font-heading mt-6 mb-3">Privacy & Data Protection</h3>
              <p>By enrolling in the Program, members consent to Kama Ayurveda collecting and processing personal information for Program management, marketing, and communication purposes. We respect your privacy and will not share your data with third parties without consent. For more details, please refer to our Privacy Policy.</p>
              <p>For any queries regarding the Loyalty Program, please reach out to our customer support team at: care@kamaayurveda.in</p>
              <p>Phone: 18001232031</p>
              <p>By continuing your membership, you acknowledge and agree to these Terms & Conditions. Kama Ayurveda retains the final authority on all matters related to the Program.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;
